#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Catalogue plumbing: local truth -> Supabase seed, JSON, and back.

The catalogue itself lives in catalog_data.py. This module only moves it
around:

    python scripts/catalog.py check               # validate + counts
    python scripts/catalog.py seed                # write supabase/seed.sql
    python scripts/catalog.py json                # write catalog.json
    python scripts/catalog.py push                # upsert into a live Supabase project

`push` needs SUPABASE_URL plus a service-role key in SUPABASE_SERVICE_KEY.
It is optional — the site is built from the local file either way, so a
missing key never blocks a build. The point of Supabase is to let the
catalogue be edited by a human in a table UI; the build then pulls it
back down with `pull`.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import catalog_data as data  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEED_PATH = os.path.join(ROOT, "supabase", "seed.sql")
JSON_PATH = os.path.join(ROOT, "catalog.json")

COLUMNS = ["sku", "model", "category", "subcategory", "name", "brand_mode", "specs",
           "image", "moq_oem", "moq_custom", "price_oem_usd", "price_custom_usd",
           "lead_time_oem_days", "lead_time_custom_days", "unit", "paths", "status",
           "source", "notes", "sort_order"]


def sql_lit(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, (list, dict)):
        return "'%s'" % json.dumps(v, ensure_ascii=False).replace("'", "''")
    if isinstance(v, list):
        return "array[%s]" % ", ".join(sql_lit(x) for x in v)
    return "'%s'" % str(v).replace("'", "''")


def row_values(p):
    out = []
    for c in COLUMNS:
        v = p.get(c)
        if c == "paths" and isinstance(v, list):
            out.append("array[%s]" % ", ".join(sql_lit(x) for x in v))
        elif c == "specs":
            out.append(sql_lit(v))
        else:
            out.append(sql_lit(v))
    return ", ".join(out)


def seed_sql():
    lines = [
        "-- Generated by scripts/catalog.py — do not edit by hand.",
        "-- Edit scripts/catalog_data.py and re-run: python scripts/catalog.py seed",
        "",
        "insert into public.products (%s) values" % ", ".join(COLUMNS),
    ]
    rows = ["  (%s)" % row_values(p) for p in data.PRODUCTS]
    lines.append(",\n".join(rows) + "\n")
    lines.append("on conflict (sku) do update set")
    updatable = [c for c in COLUMNS if c != "sku"]
    lines.append(",\n".join("  %s = excluded.%s" % (c, c) for c in updatable) + ";\n")
    return "\n".join(lines)


def catalog_json():
    return json.dumps(data.PRODUCTS, ensure_ascii=False, indent=1)


def validate():
    seen = set()
    problems = []
    for p in data.PRODUCTS:
        if p["sku"] in seen:
            problems.append("duplicate sku: %s" % p["sku"])
        seen.add(p["sku"])
        for key in ("sku", "category", "subcategory", "name", "specs"):
            if not p.get(key):
                problems.append("%s missing %s" % (p.get("sku"), key))
        if p["category"] == "rod":
            for key in ("length_m", "power", "action", "reel_type"):
                if key not in p["specs"]:
                    problems.append("%s specs missing %s" % (p["sku"], key))
        img = p.get("image")
        if img and not os.path.exists(os.path.join(ROOT, img)):
            problems.append("%s image missing: %s" % (p["sku"], img))
    return problems


def push():
    import urllib.request

    url = os.environ.get("SUPABASE_URL", "").rstrip("/")
    key = os.environ.get("SUPABASE_SERVICE_KEY", "")
    if not url or not key:
        print("SUPABASE_URL / SUPABASE_SERVICE_KEY not set — skipping push.")
        return 1
    req = urllib.request.Request(
        url + "/rest/v1/products?on_conflict=sku",
        data=json.dumps(data.PRODUCTS, ensure_ascii=False).encode("utf-8"),
        method="POST",
        headers={
            "apikey": key,
            "Authorization": "Bearer " + key,
            "Content-Type": "application/json",
            "Prefer": "resolution=merge-duplicates",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        print("push ok:", r.status)
    return 0


def pull():
    """Fetch the live table and rewrite catalog.json from it."""
    import urllib.request

    url = os.environ.get("SUPABASE_URL", "").rstrip("/")
    key = os.environ.get("SUPABASE_SERVICE_KEY", "")
    if not url or not key:
        print("SUPABASE_URL / SUPABASE_SERVICE_KEY not set — skipping pull.")
        return 1
    req = urllib.request.Request(
        url + "/rest/v1/products?select=*&order=sort_order.asc,sku.asc",
        headers={"apikey": key, "Authorization": "Bearer " + key},
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        rows = json.loads(r.read().decode("utf-8"))
    with open(JSON_PATH, "w", encoding="utf-8") as fh:
        json.dump(rows, fh, ensure_ascii=False, indent=1)
    print("pulled %d rows -> %s" % (len(rows), JSON_PATH))
    return 0


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "check"
    problems = validate()
    if problems:
        for p in problems:
            print("PROBLEM:", p)
        return 1
    print("catalogue ok: %d skus" % len(data.PRODUCTS))
    if cmd == "check":
        return 0
    if cmd == "seed":
        with open(SEED_PATH, "w", encoding="utf-8") as fh:
            fh.write(seed_sql())
        print("wrote", SEED_PATH)
    elif cmd == "json":
        with open(JSON_PATH, "w", encoding="utf-8") as fh:
            fh.write(catalog_json())
        print("wrote", JSON_PATH)
    elif cmd == "push":
        return push()
    elif cmd == "pull":
        return pull()
    else:
        print("unknown command:", cmd)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
